// @TODO '=?', '=like', '=ilike'

export const NOT = '!'
export const OR = '|'
export const AND = '&'
export const LIKE = 'like'
export const ILIKE = 'ilike'
export const NOT_ILIKE = 'not ilike'
export const NOT_LIKE = 'not like'
export const IN = 'in'
export const NOT_IN = 'not in'
export const CHILD_OF = 'child_of'
export const EQUAL = '='
export const NOT_EQUAL = '!='
export const GT = '>'
export const GTE = '>='
export const LT = '<'
export const LTE = '<='
