export const CALL = 'CALL'
export const LIST = 'LIST'
export const BUTTON = 'BUTTON'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const REPORT = 'REPORT'
export const ACTION_LOAD = 'ACTION_LOAD'
export const IMAGE = 'IMAGE'
